parserOptions:
  ecmaVersion: 2018
  sourceType: module

env:
  es6: true
  browser: true
  commonjs: true
  node: true

extends:
  - eslint:recommended

rules:
  no-trailing-spaces:
    - error

plugins:
  - pug
